### ISSUE TITLE
Implement Validation framework

### ISSUE THREAD

**Issue by rathilavkesh** [rathilavkesh/BlogRepository#11]
Implement Validation framework for mongodb

**Comment by rathilavkesh** [comment]
Added support for validation framework.

**Comment by saurabhjava2** [comment]
We need validation on the mongodb side, like email of the user should be unique, infact first name also to be unique. Now it raises a question that do we need to have a ability to have a another field of "display name" apart from first or last name, and display name should be unique.

Currently it is allowing multiple entries with same user details.
